### PR TITLE
audio/flac,audio/wav: Update to the audio v2 API.

### PR DESCRIPTION
**Pull request by mewmew**

### CODE REVIEW

**Comment by mewmew** [comment]
ref: azul3d/engine#76

**Comment by mewmew** [comment]
Hi @slimsag,

Glad to see you are also still awake :)

**Comment by slimsag** [comment]
Haha 5pm here :) Glad to see you weren't angered by my massive (and perhaps quite quick) changes!

This change looks great!

One minor nit though, could you change the commit message for 4a04b18 (the audio/wav change), currently it reads:

```
audio/flac: Update to the audio v2 API. Drop semver import paths.

vs:
audio/wav: Update to the audio v2 API. Drop semver import paths.
```

So glad once we merge this we can start using it :P

**Comment by mewmew** [comment]
Done!

**Comment by slimsag** [comment]
LGTM

**Pull request merged**
